# Generated by Django 2.2.4 on 2020-05-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200513_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='product_item',
        ),
    ]
