# Generated by Django 3.0.4 on 2020-05-14 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200513_1549'),
        ('cart', '0003_auto_20200513_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
