# Generated by Django 2.2.4 on 2020-05-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200522_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
